import { useState } from 'react'
import Head from 'next/head'
import Card from '../src/components/Card'

function Home({ dataPosts, wpTotalpages }) {
  const [posts, setPosts] = useState(dataPosts)
  const [curPage, setCurPage] = useState(1)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto mt-2">
        <div className="p-4 flex justify-between flex-wrap mt-2">
          <Card posts={posts} />
        </div>

        <button
          className="btnLoadMore"
          onClick={async () => {
            const newPosts = await getNewPostsFromApi({ curPage })
            setPosts([...posts, ...newPosts])
            setCurPage(curPage + 1)
          }}
          type="button"
        >
          Carregar mais publicações
        </button>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch(`${process.env.URL_BASE}`)
  const data = await res.json()
  console.log(data)
  return {
    props: {
      dataPosts: data,
      wpTotalpages: res.headers.get('x-wp-totalpages')
    }
  }
}

async function getNewPostsFromApi(curPage) {
  curPage.curPage += 1
  const res = await fetch(
    `https://blog.apiki.com/wp-json/wp/v2/posts?_embed&categories=518&page=${curPage.curPage}`
  )

  const data = await res.json()
  return data
}

export default Home
