// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Properties.Data;

namespace APILeases.Migrations
{
    [DbContext(typeof(PropertyContext))]
    partial class PropertyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Properties.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Habitation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Propertie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "More na região nobre de Bh",
                            Habitation = "Apartamento 4 quartos 2 vagas de garagem",
                            Picture = "https://resizedimgs.vivareal.com/fit-in/870x653/vr.images.sp/af1a4a2776fd3a38585b08608cd0b6c7.jpg",
                            Price = 2599,
                            Region = "Belo Horizonte",
                            Title = "Apartamento Luxo Bh"
                        },
                        new
                        {
                            Id = 2,
                            Description = "More na Sul de Bh",
                            Habitation = "Apartamento 3 quartos 2 vagas de garagem",
                            Picture = "https://resizedimgs.zapimoveis.com.br/fit-in/800x360/vr.images.sp/72e21bc777bca84140621cd0672e6ee8.jpg",
                            Price = 1899,
                            Region = "Belo Horizonte",
                            Title = "Apartamento Padrão Bh"
                        },
                        new
                        {
                            Id = 3,
                            Description = "More na região central de Betim",
                            Habitation = "Apartamento 3 quartos 1 vagas de garagem",
                            Picture = "https://resizedimgs.vivareal.com/fit-in/870x653/vr.images.sp/c8424f53d4482bce5e9fae7f5fd08ac2.jpg",
                            Price = 1599,
                            Region = "Betim",
                            Title = "Apartamento em Betim"
                        },
                        new
                        {
                            Id = 4,
                            Description = "região noroeste da cidade facil acesso",
                            Habitation = "Casa 3 quartos 1 vagas de garagem",
                            Picture = "https://resizedimgs.vivareal.com/fit-in/870x653/vr.images.sp/dc68069d6b172f4116f53941fd36480e.jpg",
                            Price = 1299,
                            Region = "Belo Horizonte",
                            Title = "Casa Ampla em BH"
                        },
                        new
                        {
                            Id = 5,
                            Description = "More na região nobre de Bh",
                            Habitation = "Apartamento 2 quartos 1 vagas de garagem",
                            Picture = "https://resizedimgs.vivareal.com/fit-in/870x653/vr.images.sp/005fa8a25dbffd08cc12b0f1a935334e.jpg",
                            Price = 2099,
                            Region = "Belo Horizonte",
                            Title = "Casa em Venda Nova"
                        },
                        new
                        {
                            Id = 6,
                            Description = "More na região nobre de Bh",
                            Habitation = "Apartamento 4 quartos 2 vagas de garagem",
                            Picture = "https://resizedimgs.vivareal.com/fit-in/870x653/vr.images.sp/8c95853f2e99ab3bcbe1aae861aaef8d.jpg",
                            Price = 2599,
                            Region = "Belo Horizonte",
                            Title = "Casa no Barreiro"
                        },
                        new
                        {
                            Id = 7,
                            Description = "More na região central de Contagem",
                            Habitation = "Apartamento 4 quartos 2 vagas de garagem",
                            Picture = "https://www.quintoandar.com.br/img/med/892939726-362.2953385371208DSC7172.jpg",
                            Price = 1299,
                            Region = "Contagem",
                            Title = "Apartamento Contagem"
                        },
                        new
                        {
                            Id = 8,
                            Description = "More na região nobre de Bh",
                            Habitation = "Apartamento 3 quartos 2 vagas de garagem",
                            Picture = "https://resizedimgs.vivareal.com/fit-in/870x653/vr.images.sp/afb129df59406c355e0c245b3e321f0c.jpg",
                            Price = 3599,
                            Region = "Belo Horizonte",
                            Title = "Casa Luxo Bh"
                        },
                        new
                        {
                            Id = 9,
                            Description = "More na região norte de Bh",
                            Habitation = "Apartamento 2 quartos 2 vagas de garagem",
                            Picture = "https://www.quintoandar.com.br/img/med/892953412-268.6248211630229DSC1104.jpg",
                            Price = 2699,
                            Region = "Belo Horizonte",
                            Title = "Casa Padrão Bh"
                        },
                        new
                        {
                            Id = 10,
                            Description = "More no centro de Betim",
                            Habitation = "Apartamento 1 quartos sem vaga de garagem",
                            Picture = "https://www.quintoandar.com.br/img/med/892939726-362.2953385371208DSC7172.jpg",
                            Price = 1499,
                            Region = "Betim",
                            Title = "Casa em Betim"
                        },
                        new
                        {
                            Id = 11,
                            Description = "More no centro de Contagem",
                            Habitation = "Apartamento 2 quartos 2 vagas de garagem",
                            Picture = "https://www.quintoandar.com.br/img/med/893218656-360.1517375526222hudsonbuchholzhgbfotos25de33.jpg",
                            Price = 1399,
                            Region = "Contagem",
                            Title = "Casa em Contagem"
                        },
                        new
                        {
                            Id = 12,
                            Description = "More perto dos hospitais, excelente localização",
                            Habitation = "Casa 5 quartos 4 vagas de garagem",
                            Picture = "https://www.quintoandar.com.br/img/med/892942267-901.0890635282618IMG4610.JPG",
                            Price = 2599,
                            Region = "Betim",
                            Title = "Casa Grande em Betim"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
