import Head from 'next/head';

export function HomeScreen() {
  return (
    <>
      <Head>
        <title>Apiki Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <main>

      </main>
    </>
  )
}