import Head from 'next/head';
import { useEffect, useState } from 'react';
import axios from 'axios';

import { PostCard } from '@/components/PostCard';

import { 
  PostsListWrapper, 
  ShowMoreButton
} from './style';
import { ScrollToTopButton } from '@/components/ScrollToTopButton';

export function HomeScreen() {
  const [posts, setPosts] = useState([]);
  const [page, setPage] = useState(1);
  const [totalPage, setTotalPage] = useState(0);

  const getPosts = async () => {
    const response = await axios.get(`https://blog.apiki.com/wp-json/wp/v2/posts?_embed&categories=518&page=${page}`);
    
    setPosts(response.data);
    setTotalPage(response.headers['x-wp-totalpages']);
  }

  const loadMore = async () => {
    setPage(page + 1);

    if(page === totalPage) {
      return;
    } else {
      const response = axios.get(`https://blog.apiki.com/wp-json/wp/v2/posts?_embed&categories=518&page=${page}`);
      setPosts(posts.concat((await response).data));
    }
  }

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <>
      <Head>
        <title>Apiki Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <PostsListWrapper>
        {posts.map((post, index) => (
          <PostCard  
            key={post.id + index}
            post={post} 
          />
        ))}
      </PostsListWrapper>
      <ShowMoreButton onClick={loadMore}>carregar mais...</ShowMoreButton>
      <ScrollToTopButton />
    </>
  )
}